### ISSUE TITLE
Check WPGB before syncing facets

### ISSUE THREAD

**Issue by lhall-amphibee** [AmphiBee/wpgb-extended#3]
WPGB extended doesn't check if WP Grid Builder is enabled before syncing, which can cause a website crash :

```
PHP Fatal error:  Uncaught Error: Class 'WP_Grid_Builder\Includes\Database' not found in /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Models/Facet.php:22
Stack trace:
#0 [internal function]: AmphiBee\WpgbExtended\Models\Facet::getBySlug()
#1 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Providers/ItemSync.php(83): call_user_func()
#2 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Providers/ItemSync.php(74): AmphiBee\WpgbExtended\Providers\ItemSync->getItem()
#3 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Core/Hooks/SyncManager.php(18): AmphiBee\WpgbExtended\Providers\ItemSync->importOrUpdate()
#4 [internal function]: AmphiBee\WpgbExtended\Core\Hooks\SyncManager->execute()
#5 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/vendor/amphibee/hookable/src/Hook.php(69): call_user_func_array( in /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Models/Facet.php on line 22
Fatal error: Uncaught Error: Class 'WP_Grid_Builder\Includes\Database' not found in /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Models/Facet.php:22
Stack trace:
#0 [internal function]: AmphiBee\WpgbExtended\Models\Facet::getBySlug()
#1 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Providers/ItemSync.php(83): call_user_func()
#2 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Providers/ItemSync.php(74): AmphiBee\WpgbExtended\Providers\ItemSync->getItem()
#3 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Core/Hooks/SyncManager.php(18): AmphiBee\WpgbExtended\Providers\ItemSync->importOrUpdate()
#4 [internal function]: AmphiBee\WpgbExtended\Core\Hooks\SyncManager->execute()
#5 /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/vendor/amphibee/hookable/src/Hook.php(69): call_user_func_array( in /var/www/releases/87432561bf329a5059014949a57117451a2c7c8f/web/app/mu-plugins/wpgb-extended/src/Models/Facet.php on line 22
```

**Comment by ogorzalka** [comment]
Added in the todolist @lhall-amphibee 🙂

**Comment by quentinhnrt** [comment]
I made a pull request to fix it #12

**Comment by ogorzalka** [comment]
I think we could make it easier without testing the class existence. I check this this week

**Comment by ogorzalka** [comment]
Fixed with https://github.com/AmphiBee/wpgb-extended/commit/243cf3c722df78ed5ed35c36b3cd98590ac85d67
